{
 "title": "App DevOps",
 "panels": [
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Latencia p95",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Version activa",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{job}}" }
   ]
  }
 ]
}